name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
<<<<<<< HEAD
        uses: aglipanci/laravel-pint-action@2.4
=======
        uses: aglipanci/laravel-pint-action@2.1.0
>>>>>>> 0ed41ba (Bump aglipanci/laravel-pint-action from 1.0.0 to 2.1.0)

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
